resolver: lts-6.3
packages:
- '.'
- location:
    git: https://github.com/esmolanka/sexp-grammar.git
    commit: 427e4b128b2633d93d34095982191765dbcc3bcf
extra-deps:
# - sexp-grammar-1.2.1
- recursion-schemes-4.1.2
